#!/usr/bin/env php
<?php
if(!isset($argv[1])) {
  echo "Domain required\n";
  exit(1);
}


chdir(__DIR__);
require('vendor/autoload.php');

use Choval\Async;
use Choval\Whois\Query;
use Choval\Whois\Factory;

$loop = Async\init();

$whois = new Factory($loop);
$res = Async\wait( $whois->query($argv[1])->run() );
echo "QUERY: ".$res->getAddress().PHP_EOL;
echo "COUNTRY: ".$res->getCountry().PHP_EOL;
echo "OWNER: ".$res->getOwner().PHP_EOL;

